version: "3.9"
services:
    db:
        image: "postgres"
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=db
        volumes:
            - ./pgdata:/var/lib/postgres/data
        ports:
            - "64325:5432"
    nodejs:
        build: ./
        ports:
          - "3001:3001"
        environment:
            - EXTERNAL_PORT=3001
            - PGUSER=postgres
            - PGPASSWORD=postgres
            - PGDATABASE=example
            - PGHOST=db # NAME OF THE SERVICE
        depends_on:
            - db
